Emailer.emailerror: accepts list of recipients Fpiinfo: adding minime11,12 and 10, blo,low sites X300Sensor.WriteLogFromRaw: accepts number of sensing device. This version reads homeassistant and rpi files handled  by Zipper.py FPI.ParameterFit: added sky_line_tag to process different type of airglow images like green line 577 tagged with XG. Any G in sky_line_tag will switch to use frequency lam0_gl in fpiinfo otherwise lam0 is used. FPIDisplay.PlotDiagnosticFig: added panel for zigbee/rpi sensors if files exist.